import React, { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import "../public/build/tailwind.css";
import "./styles.css";
import { fetchContactRequest, fetchHireRequest } from "../js/API-fetch.js";
import bulletinData from "../js/bulletin/bulletinData.js";
import codingTrackerData from "../js/code-log/codingTrackerData.js";
import b3Thumbnail from "../assets/B3Thumbnail.png";
import astThumbnail from "../assets/astThumbnail.png";
import careerThumbnail from "../assets/thumbnail.png";

const navItems = [["Home", "/"], ["Library", "/library"], ["Projects", "/project"]];

function Header({ onHire }) {
  const path = window.location.pathname;
  return <header className="sticky top-0 z-50 border-b border-white/10 bg-black/70 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-6">
    <a href="/" className="inline-flex items-center"><img src="/api/assets/logo" alt="BuiltByBugs" className="block h-11 w-auto" /></a>
    <nav aria-label="Primary navigation"><ul className="hidden gap-8 text-sm md:flex">{navItems.map(([label, href]) => <li key={href}><a href={href} className={`nav-link transition-colors hover:text-cyan-400 ${path === href || (href === "/" && path === "/index.html") ? "text-cyan-400" : ""}`}>{label}</a></li>)}<li><a href="#contact" onClick={(e) => { e.preventDefault(); window.dispatchEvent(new Event("open-contact")); }} className="nav-link transition-colors hover:text-cyan-400">Contact</a></li></ul></nav>
    <button onClick={onHire} className="rounded-lg border border-slate-700 px-5 py-2 text-sm transition hover:border-cyan-400 hover:text-cyan-400">Hire Me</button>
  </div></header>;
}

function Canvas() {
  useEffect(() => { let active = true; import("../js/theme.js").then(({ initCanvas }) => active && initCanvas()); return () => { active = false; }; }, []);
  return <canvas id="backgroundCanvas" className="pointer-events-none absolute inset-0 -z-10" />;
}

function Modal({ type, onClose }) {
  const hire = type === "hire"; const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function submit(e) { e.preventDefault(); setBusy(true); setError(""); const data = Object.fromEntries(new FormData(e.currentTarget)); try { const result = hire ? await fetchHireRequest(data.name, data.email, data.message) : await fetchContactRequest(data.email, data.message); if (result?.success === false) throw new Error(result.error || "Request failed"); e.currentTarget.reset(); onClose(); } catch (err) { setError(err.message || "Something went wrong. Please try again."); } finally { setBusy(false); } }
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-6" role="dialog" aria-modal="true" onMouseDown={(e) => e.target === e.currentTarget && onClose()}><div className="w-full max-w-lg rounded-xl border border-slate-700 bg-slate-950 p-7 shadow-2xl"><div className="mb-6 flex items-center justify-between"><h2 className="text-xl font-bold">{hire ? "Start a project" : "Get in touch"}</h2><button onClick={onClose} className="rounded-lg p-2 text-2xl hover:bg-slate-800" aria-label="Close">×</button></div><form onSubmit={submit} className="space-y-5">{hire && <label className="block text-sm text-slate-400">Name<input name="name" required className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-900 px-4 py-3 outline-none focus:border-cyan-400" /></label>}<label className="block text-sm text-slate-400">Email<input name="email" type="email" required className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-900 px-4 py-3 outline-none focus:border-cyan-400" /></label><label className="block text-sm text-slate-400">Message<textarea name="message" required rows="4" className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-900 px-4 py-3 outline-none focus:border-cyan-400" /></label>{error && <p className="text-sm text-rose-400">{error}</p>}<button disabled={busy} className="rounded-lg bg-cyan-500 px-5 py-3 font-medium text-slate-950 hover:bg-cyan-400 disabled:opacity-50">{busy ? "Sending…" : hire ? "Send Request" : "Send"}</button></form></div></div>;
}

function Activity() { const bulletin = bulletinData?.slice?.(0, 4) || []; const tracker = codingTrackerData?.weekly ? [["This week", `${codingTrackerData.weekly.commits} commits`], ["Files changed", codingTrackerData.weekly.filesChanged], ["Current streak", `${codingTrackerData.streak.current} days`], ["Today", `${codingTrackerData.today.hours} hours`]] : []; return <section className="mx-auto max-w-7xl px-6 py-20" data-reveal><div className="flex flex-wrap justify-center gap-8"><div className="h-[360px] w-[360px] rounded-xl border border-slate-800 bg-blued p-6"><h2 className="text-2xl font-bold">Development Activity</h2><p className="mt-2 text-slate-400">Current progress across coding platforms and ongoing work.</p><div className="mt-6 space-y-3 text-sm text-slate-400">{bulletin.map((item, i) => <p key={i} className="border-l-2 border-cyan-400 pl-3">{item.title || item.text || "Building in public"}</p>)}</div></div><div className="h-[360px] w-[360px] rounded-xl border border-slate-800 bg-blued p-6"><h3 className="text-xl font-semibold">GitHub</h3><p className="mt-2 text-slate-400">Contribution data is loaded from the portfolio API.</p><div className="mt-8 grid grid-cols-7 gap-2">{Array.from({ length: 35 }, (_, i) => <span key={i} className={`h-4 rounded-sm ${i % 5 === 0 ? "bg-cyan-400" : i % 3 === 0 ? "bg-cyan-900" : "bg-slate-800"}`} />)}</div></div><div className="h-[360px] w-[360px] rounded-xl border border-slate-800 bg-blued p-6"><h3 className="text-xl font-semibold">Coding Tracker</h3><p className="mt-2 text-slate-400">Recent sessions and consistent practice.</p><div className="mt-7 space-y-3">{tracker.map(([label, value]) => <div key={label} className="flex items-center justify-between text-sm"><span className="text-slate-400">{label}</span><span className="text-cyan-400">{value}</span></div>)}</div></div></div></section>; }

function Footer({ onContact }) { return <footer className="border-slate-800 bg-black" data-reveal><div className="mx-auto max-w-7xl px-6 py-14"><div className="grid items-start gap-12 md:grid-cols-[1fr_auto_auto]"><div><h3 className="text-lg font-semibold">OCDbug<span className="align-top text-[10px]">™</span></h3><p className="mt-2 text-sm text-slate-500">Personal site by OCDbug.</p></div><div><p className="mb-3 text-xs uppercase tracking-[0.2em] text-slate-500">Navigation</p><div className="flex gap-6 text-sm text-slate-400">{navItems.map(([label, href]) => <a href={href} key={href} className="transition hover:text-cyan-400">{label}</a>)}</div></div><div><p className="mb-3 text-xs uppercase tracking-[0.2em] text-slate-500">Contact</p><button onClick={onContact} className="text-sm text-slate-400 transition hover:text-cyan-400">Start a conversation →</button></div></div></div></footer>; }

function Home({ onContact }) { return <><main className="relative flex-1"><Canvas /><section className="mx-auto flex max-w-6xl flex-col gap-16 px-6 py-24" data-reveal><div className="space-y-6"><span className="inline-block rounded-full border border-cyan-500/40 px-4 py-1 text-sm text-cyan-300">Available for Work</span><h1 className="text-5xl font-bold leading-tight md:text-6xl">Hi, I'm <span className="text-cyan-400">Piyush</span></h1><p className="max-w-2xl text-lg leading-8 text-slate-400">I create, design and program software. Currently focused on backend development, automation and building useful developer tools.</p><div className="flex flex-wrap gap-4"><a href="/project" className="rounded-lg bg-cyan-500 px-6 py-3 font-medium text-slate-950 hover:bg-cyan-400">View Projects</a><button onClick={onContact} className="rounded-lg border border-slate-700 px-6 py-3 hover:border-cyan-400 hover:text-cyan-400">Contact Me</button></div></div></section><Activity /><section className="mx-auto flex max-w-6xl flex-col gap-8 px-6 py-24" data-reveal><h2 className="text-2xl font-bold text-cyan-400">What I Build</h2><p className="max-w-3xl leading-8 text-slate-400">I enjoy designing software from first principles. My interests lie in backend systems, developer tooling, compiler techniques, automation and maintainable architectures.</p><div className="flex flex-wrap gap-4">{["JavaScript (ES Modules)", "Node.js", "Backend APIs", "AST Analysis", "Rule Engine Design", "Automation", "System Architecture", "REST APIs", "Git & GitHub"].map((tag) => <span className="rounded-full border border-lime-400 px-4 py-2 text-sm" key={tag}>{tag}</span>)}</div></section></main><Footer onContact={onContact} /></>; }

const projects = [{ title: "BuiltByBugs", desc: "Personal portfolio showcasing custom frontend, backend APIs and handcrafted UI architecture.", tech: "HTML • CSS • JavaScript • Node.js", image: b3Thumbnail, status: "Live" }, { title: "AST Rule Engine", desc: "A custom Abstract Syntax Tree rule engine focused on source-code analysis and transformation.", tech: "JavaScript • Node.js • AST", image: astThumbnail, status: "In Progress", github: "https://github.com/Piyush07-lab/ast" }, { title: "Job Portal", desc: "Recruitment platform featuring resume evaluation and ATS analysis.", tech: "React • Express • MongoDB", image: careerThumbnail, status: "In Progress", live: "https://job-portal-eight-roan.vercel.app/", github: "https://github.com/PrashantMishra10232/Job_Portal" }, { title: "Music Application", desc: "Modern music streaming application with a clean listening experience.", tech: "React • Node.js", status: "Planning" }];
function Projects({ onContact }) { return <><main className="relative flex-1"><Canvas /><section className="mx-auto max-w-7xl px-6 py-24" data-reveal><h1 className="text-5xl font-bold tracking-tight">Projects</h1><p className="mt-6 max-w-3xl leading-8 text-slate-400">Selected work spanning frontend experiences, backend systems and developer tooling.</p><div className="mt-14 flex flex-wrap justify-center gap-8">{projects.map((p) => <article key={p.title} className="flex h-[420px] w-[360px] flex-col rounded-xl border border-slate-800 bg-blued p-6" data-reveal><div className="mb-6 flex h-40 items-center justify-center overflow-hidden rounded-lg border border-dashed border-slate-700 text-slate-500">{p.image ? <img src={p.image} alt="" className="h-full w-full object-cover" /> : "Thumbnail"}</div><span className="mb-4 inline-block w-fit rounded-full border border-cyan-500/30 px-3 py-1 text-xs text-cyan-300">{p.status}</span><h2 className="text-2xl font-bold">{p.title}</h2><p className="mt-3 flex-1 leading-7 text-slate-400">{p.desc}</p><div className="mt-5 text-sm text-slate-500">{p.tech}</div><div className="mt-6 flex gap-4">{p.live && <a href={p.live} target="_blank" rel="noreferrer" className="rounded-lg bg-cyan-500 px-4 py-2 font-medium text-slate-950 hover:bg-cyan-400">Live Preview</a>}{p.github && <a href={p.github} target="_blank" rel="noreferrer" className="rounded-lg border border-slate-700 px-4 py-2 hover:border-cyan-400 hover:text-cyan-400">GitHub</a>}</div></article>)}</div><div className="mt-24 rounded-xl border border-slate-800 bg-blued p-8"><h2 className="text-3xl font-bold">Repository Showcase</h2><p className="mt-2 text-slate-400">Live repositories, contribution statistics and project metadata will appear here.</p></div></section></main><Footer onContact={onContact} /></>; }

const articles = [{ id: "ast-engine", tag: "Engineering", title: "Why I Built My Own AST Engine", body: "Building an Abstract Syntax Tree engine from scratch taught me far more about parsing, traversal and maintainable software architecture than relying on existing tooling ever could. The modular pipeline is designed for diagnostics, custom rules and future source transformations." }, { id: "deterministic-systems", tag: "Architecture", title: "Designing Deterministic Systems", body: "Given the same inputs, a system should always produce the same output. Clear data flow, explicit state transitions and immutable histories make complex applications easier to debug, test and maintain." }, { id: "learning-through-building", tag: "Philosophy", title: "Learning Through Building", body: "I learn best by building software instead of collecting tutorials. Each project becomes a record of decisions, trade-offs and lessons that strengthen engineering judgement." }];
function Library({ onContact }) { return <><main className="relative flex-1"><Canvas /><section className="mx-auto max-w-6xl px-6 py-24"><h1 className="text-5xl font-bold tracking-tight">Library</h1><div className="mt-16 space-y-16">{articles.map((a) => <article id={a.id} key={a.id} className="rounded-xl border border-slate-800 bg-slate-900/30 p-10" data-reveal><span className="inline-block rounded-full border border-cyan-500/30 px-3 py-1 text-xs text-cyan-300">{a.tag}</span><h2 className="mt-5 text-3xl font-bold">{a.title}</h2><p className="mt-8 max-w-4xl leading-8 text-slate-400">{a.body}</p></article>)}</div></section></main><Footer onContact={onContact} /></>; }

function App() { const [modal, setModal] = useState(null); const [path, setPath] = useState(window.location.pathname); useEffect(() => { const open = () => setModal("contact"); window.addEventListener("open-contact", open); const update = () => setTimeout(() => setPath(window.location.pathname), 0); window.addEventListener("popstate", update); return () => { window.removeEventListener("open-contact", open); window.removeEventListener("popstate", update); }; }, []); const page = path.includes("library") ? <Library onContact={() => setModal("contact")} /> : path.includes("project") ? <Projects onContact={() => setModal("contact")} /> : <Home onContact={() => setModal("contact")} />; return <div className="flex min-h-screen flex-col"><Header onHire={() => setModal("hire")} />{page}{modal && <Modal type={modal} onClose={() => setModal(null)} />}</div>; }

createRoot(document.getElementById("root")).render(<React.StrictMode><App /></React.StrictMode>);
